### ISSUE TITLE
HELP QUESTION Research usage with https://servestjs.org

### ISSUE THREAD

**Issue by ldexterldesign** [denyncrawford/deno-livereload#2]
Hi!

Thanks for software

> To use LiveReload you must create a server and then inject some code in your html

I'm using [Servest static HTTP file server] (I'm sure other Deno newbs will come across this quickly too) - do you know if your module will work with it or do I need a [Servest dynamic HTTP filer server]?

---

Also, would you be kind enough to elaborate on how [building the web client] works?

I ran the Deno script to bundle but don't see a `client.js` file generated for use in the HTML?

Hope to hear back

Sincerely

[Servest dynamic HTTP filer server]: https://servestjs.org/app-api / https://servestjs.org/agent-api / https://servestjs.org/server-api
[Servest static file server]: https://servestjs.org/use-serve-static
[building the web client]: https://github.com/denyncrawford/deno-livereload#building-the-web-client
[source]: https://github.com/denyncrawford/deno-livereload#usage

**Comment by denyncrawford** [comment]
Hi dude! Sure, you can check the new examples folder, it can give you an idea of how you can work with server frameworks including servest. But I think you mean that you are not being able to use the same server with the live handler and I'm sorry to tell that I don't know if it could be posible, at least with servest. It should work with any server framework that uses the std http `ServerRequest`  interface, and [as you can see here](https://github.com/keroxp/servest/blob/2852318072f5b3f2f14fd20f563f3fff6e2f7c0c/server.ts#L71) servest uses its own interfaces wich means that I would need to adapt dropper (the ws framework) just to support servest, and seems unnecessary to me. 

To port the servest request, you maybe should do some type of interface that rewrites the servest one to pass it as the std request object and then use it in the live handler method, but it is overkilled too.

Live reload is stand alone by default, so you can run both servers in different ports and it will work fine as in the servest example.

About the client thing, I think you're miss understanding the client: it is not intended to be used manually, actually the client builds everytime a request is made to the file endpoint so the file is being served automatically, the client bundle is just for internal usage, the only thing you need to do is add the script pointing to the `/livereload/client.js` route. 
**Eg**: `<script src="http://localhost:39430/livereload/client.js" defer></script>`

This is because it uses the dynamic port and the protocol of the server so you don't have to set manually the websockets client.

If you want to use the client module on your own, it is just a function that receives the port and the protocol then it returns a string wich is the actual bundle. So  you can write it or serve it as `application/javascript`.

I'll leave this open for a while, if you have another question just drop it 😄.
